[workspace]
members = [
    "packages/bao_core",
    "packages/bao_collections",
    "packages/bao_unicode",
    "packages/bao_hash",
    "packages/bao_path",
    "packages/bao_sys",
    "packages/bao_io",
    "packages/bao_threading",
    "packages/bao_event_loop",
    "packages/bao_parser",
    "packages/bao_runtime",
    "packages/bao_http",
    "packages/bao_bundler",
    "packages/bao_install",
    "packages/bao_sql",
    "packages/bao_cli",
    "packages/bao_transpiler",
    "packages/bao_resolver",
    "packages/bao_dotenv",
    "packages/bao_semver",
    "packages/bao_base64",
    "packages/bao_sourcemap",
    "packages/bao_zlib",
    "packages/bao_brotli",
    "packages/bao_zstd",
    "packages/bao_jsc",
    "packages/bao_ast",
    "packages/bao_parsers",
    "packages/bao_shell_parser",
    "packages/bao_spawn",
    "packages/bao_router",
    "packages/bao_url",
    "packages/bao_ini",
    "packages/bao_dns",
    "packages/bao_glob",
    "packages/bao_bun_alloc",
    "packages/bao_ptr",
    "packages/bao_string",
    "packages/bao_s3_signing",
    "packages/bao_md",
]
build-members = [
    "packages/bao_core",
    "packages/bao_collections",
    "packages/bao_unicode",
    "packages/bao_hash",
    "packages/bao_path",
    "packages/bao_sys",
    "packages/bao_io",
    "packages/bao_threading",
    "packages/bao_event_loop",
    "packages/bao_parser",
    "packages/bao_runtime",
    "packages/bao_http",
    "packages/bao_bundler",
    "packages/bao_install",
    "packages/bao_sql",
    "packages/bao_cli",
    "packages/bao_transpiler",
    "packages/bao_resolver",
    "packages/bao_dotenv",
    "packages/bao_semver",
    "packages/bao_base64",
    "packages/bao_sourcemap",
    "packages/bao_zlib",
    "packages/bao_brotli",
    "packages/bao_zstd",
    "packages/bao_jsc",
    "packages/bao_ast",
    "packages/bao_parsers",
    "packages/bao_shell_parser",
    "packages/bao_spawn",
    "packages/bao_router",
    "packages/bao_url",
    "packages/bao_ini",
    "packages/bao_dns",
    "packages/bao_glob",
    "packages/bao_bun_alloc",
    "packages/bao_ptr",
    "packages/bao_string",
    "packages/bao_s3_signing",
    "packages/bao_md",
]
test-members = [
    "packages/bao_core",
    "packages/bao_collections",
    "packages/bao_unicode",
    "packages/bao_hash",
]
compile-option = ""
override-compile-option = ""
link-option = ""
target-dir = "target"
