[package]
cjc-version = "1.0.0"
name = "bao_min_cli"
organization = "bao"
description = "Minimal Bao CLI bootstrap target"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "executable"
src-dir = "src"
target-dir = ""

[dependencies]
