[package]
cjc-version = "1.0.0"
name = "bao_path"
organization = "bao"
description = "Bao file path handling: PathString, PathBuffer, platform path operations"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
bao_sys = { path = "../bao_sys" }
bao_core = { path = "../bao_core" }
