[package]
cjc-version = "1.0.0"
name = "bao_cli"
organization = "bao"
description = "Bao CLI entry point: run, build, install, test, init commands"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "executable"
src-dir = "src"
target-dir = ""

[dependencies]
bao_sys = { path = "../bao_sys" }
bao_sql = { path = "../bao_sql" }
bao_runtime = { path = "../bao_runtime" }
bao_resolver = { path = "../bao_resolver" }
bao_path = { path = "../bao_path" }
bao_parser = { path = "../bao_parser" }
bao_jsc = { path = "../bao_jsc" }
bao_io = { path = "../bao_io" }
bao_install = { path = "../bao_install" }
bao_http = { path = "../bao_http" }
bao_hash = { path = "../bao_hash" }
bao_core = { path = "../bao_core" }
bao_collections = { path = "../bao_collections" }
bao_bundler = { path = "../bao_bundler" }
