[package]
cjc-version = "1.0.0"
name = "bao_io"
organization = "bao"
description = "Bao IO operations: file reading/writing, streams, buffered IO"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "library"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
bao_sys = { path = "../bao_sys" }
