[package]
cjc-version = "1.0.0"
name = "bao_string"
organization = "bao"
description = "Bao string utilities: immutable strings, StringBuilder, SmolStr, WTF encoding"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
bao_unicode = { path = "../bao_unicode" }
bao_core = { path = "../bao_core" }
