[package]
cjc-version = "1.0.0"
name = "bao_tcc_sys"
organization = "bao"
description = "TinyCC (TCC) FFI bindings"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "library"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
