[package]
cjc-version = "1.0.0"
name = "bao_watcher"
organization = "bao"
description = "Bao bao_watcher module"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
bao_threading = { path = "../bao_threading" }
bao_sys = { path = "../bao_sys" }
bao_event_loop = { path = "../bao_event_loop" }
bao_core = { path = "../bao_core" }
