[package]
cjc-version = "1.0.0"
name = "bao_http"
organization = "bao"
description = "Bao HTTP server and client: request, response, headers, WebSocket"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "library"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
bao_io = { path = "../bao_io" }
bao_sys = { path = "../bao_sys" }
bao_event_loop = { path = "../bao_event_loop" }
bao_threading = { path = "../bao_threading" }
