[package]
cjc-version = "1.0.0"
name = "bao_perf"
organization = "bao"
description = "Bao performance tracing, profiling, and hardware timer utilities"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
