[package]
cjc-version = "1.0.0"
name = "bao_meta"
organization = "bao"
description = "Bao type metaprogramming utilities, type traits, bitfield operations, and tagged unions"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
