[package]
cjc-version = "1.0.0"
name = "bao_bun_alloc"
organization = "bao"
description = "Bao memory allocation: mimalloc arena, fallback allocators, heap breakdown"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
bao_crash_handler = { path = "../bao_crash_handler" }
bao_collections = { path = "../bao_collections" }
