[package]
cjc-version = "1.0.0"
name = "bao_semver_jsc"
organization = "bao"
description = "Bao Semver JSC bindings"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "library"
src-dir = "src"
target-dir = ""

[dependencies]
bao_jsc = { path = "../bao_jsc" }
bao_core = { path = "../bao_core" }
bao_semver = { path = "../bao_semver" }
