[package]
cjc-version = "1.0.0"
name = "bao_runtime"
organization = "bao"
description = "Bao JavaScript runtime: JSC bindings, VM, Node.js API, Web API"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
bao_valkey = { path = "../bao_valkey" }
bao_threading = { path = "../bao_threading" }
bao_sys = { path = "../bao_sys" }
bao_path = { path = "../bao_path" }
bao_parser = { path = "../bao_parser" }
bao_jsc = { path = "../bao_jsc" }
bao_io = { path = "../bao_io" }
bao_event_loop = { path = "../bao_event_loop" }
bao_core = { path = "../bao_core" }
bao_collections = { path = "../bao_collections" }
bao_bun_alloc = { path = "../bao_bun_alloc" }
bao_bundler = { path = "../bao_bundler" }
bao_ptr = { path = "../bao_ptr" }
bao_watcher = { path = "../bao_watcher" }
bao_http_types = { path = "../bao_http_types" }
bao_uws_sys = { path = "../bao_uws_sys" }
bao_options = { path = "../bao_options" }
bao_simdutf_sys = { path = "../bao_simdutf_sys" }
