[package]
cjc-version = "1.0.0"
name = "bao_threading"
organization = "bao"
description = "Bao threading and concurrency: thread pool, mutex, atomic, condition variables"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "library"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
