[package]
cjc-version = "1.0.0"
name = "bao_bun_core_macros"
organization = "bao"
description = "No-op compatibility package for Bun Rust macro crate bun_core_macros"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
