[package]
cjc-version = "1.0.0"
name = "bao_router"
organization = "bao"
description = "Bao HTTP router: route patterns, URL matching, middleware, route groups"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
bao_collections = { path = "../bao_collections" }
