[package]
cjc-version = "1.0.0"
name = "bao_ptr"
organization = "bao"
description = "Bao pointer utilities: Cow, ref counting, tagged pointers, weak ptr"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
bao_threading = { path = "../bao_threading" }
