[package]
cjc-version = "1.0.0"
name = "bao_sys"
organization = "bao"
description = "Bao system bindings: OS interface, process management, DNS, file watcher, FFI"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "library"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
bao_path = { path = "../bao_path" }
