[package]
cjc-version = "1.0.0"
name = "bao_spawn_sys"
organization = "bao"
description = "POSIX spawn system bindings"
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "static"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
bao_sys = { path = "../bao_sys" }
bao_collections = { path = "../bao_collections" }
