[package]
cjc-version = "1.0.0"
name = "bao_collections"
organization = "bao"
description = "Bao collection data structures: HashMap, HashSet, ArrayList, LinkedList, etc."
version = "0.1.0"
compile-option = ""
override-compile-option = ""
link-option = ""
output-type = "library"
src-dir = "src"
target-dir = ""

[dependencies]
bao_core = { path = "../bao_core" }
